In [3]:
import pandas as pd

# Read data from your prepared example .json-file (look at w3schools.com for examples)
data = pd.read_json("cat.json")

# Print the data 
print(data)

               id          owner      secret  server  farm  \
0     51193420302   12012973@N00  a2fe5cedc6   65535    66
1     51194989028   48447300@N02  8ef61baf57   65535    66
2     51195548179   48447300@N02  558b0b2bdc   65535    66
3     51197606714  181609802@N03  0ae5f83ab2   65535    66
4     51197298805   23307937@N04  28df630fab   65535    66
...           ...            ...         ...     ...   ...
1995  51006906196  158292715@N07  cb783a180e   65535    66
1996  51016540858   23974506@N05  69666368d9   65535    66
1997  51016132921   83818540@N00  e866e52464   65535    66
1998  51016826177   67212223@N05  23b7f85e0a   65535    66
1999  51016877196   64116329@N04  5dd1143853   65535    66

                                       title  ispublic  isfriend  isfamily  \
0                                     Frends         1         0         0
1     Cousins having dinner - Happy Caturday         1         0         0
2      Waiting for her fill - Happy Caturday         1         0         0
3                         Jessie am 15.05.21         1         0         0
4                         Introducing Gentil         1         0         0
...                                      ...       ...       ...       ...
1995                           IMG_4422 Lola         1         0         0
1996                        #133 - Just Bebe         1         0         0
1997                                 Resting         1         0         0
1998                          Regard de chat         1         0         0
1999                                 Go away         1         0         0

               ownername  ...  o_height place_id      woeid  geo_is_public  \
0      Valentine Kleyner  ...       NaN      NaN        NaN            NaN
1        Finn Frode (DK)  ...    1536.0           2619940.0            1.0
2        Finn Frode (DK)  ...    1536.0           2619940.0            1.0
3              rosapfote  ...       NaN      NaN        NaN            NaN
4            frankieleon  ...    3024.0      NaN        NaN            NaN
...                  ...  ...       ...      ...        ...            ...
1995  Fernando Sa Rapita  ...    4000.0           8299683.0            1.0
1996              n8fire  ...    5464.0      NaN        NaN            NaN
1997             Arutemu  ...       NaN      NaN        NaN            NaN
1998            Mikasper  ...       NaN      NaN        NaN            NaN
1999            ..Rini..  ...       NaN      NaN        NaN            NaN

     geo_is_contact geo_is_friend geo_is_family  \
0               NaN           NaN           NaN
1               0.0           0.0           0.0
2               0.0           0.0           0.0
3               NaN           NaN           NaN
4               NaN           NaN           NaN
...             ...           ...           ...
1995            0.0           0.0           0.0
1996            NaN           NaN           NaN
1997            NaN           NaN           NaN
1998            NaN           NaN           NaN
1999            NaN           NaN           NaN

                                                  url_o  height_o  width_o
0                                                   NaN       NaN      NaN
1     https://live.staticflickr.com/65535/5119498902...    1536.0   2560.0
2     https://live.staticflickr.com/65535/5119554817...    1536.0   2048.0
3     https://live.staticflickr.com/65535/5119760671...    3120.0   4160.0
4     https://live.staticflickr.com/65535/5119729880...    3024.0   4032.0
...                                                 ...       ...      ...
1995  https://live.staticflickr.com/65535/5100690619...    4000.0   6000.0
1996  https://live.staticflickr.com/65535/5101654085...    5464.0   8192.0
1997                                                NaN       NaN      NaN
1998  https://live.staticflickr.com/65535/5101682617...    1200.0   1800.0
1999                                                NaN       NaN      NaN

[2000 rows x 34 columns]

In [4]:
print(data.isnull())

         id  owner  secret  server   farm  title  ispublic  isfriend  \
0     False  False   False   False  False  False     False     False
1     False  False   False   False  False  False     False     False
2     False  False   False   False  False  False     False     False
3     False  False   False   False  False  False     False     False
4     False  False   False   False  False  False     False     False
...     ...    ...     ...     ...    ...    ...       ...       ...
1995  False  False   False   False  False  False     False     False
1996  False  False   False   False  False  False     False     False
1997  False  False   False   False  False  False     False     False
1998  False  False   False   False  False  False     False     False
1999  False  False   False   False  False  False     False     False

      isfamily  ownername  ...  o_height  place_id  woeid  geo_is_public  \
0        False      False  ...      True      True   True           True
1        False      False  ...     False     False  False          False
2        False      False  ...     False     False  False          False
3        False      False  ...      True      True   True           True
4        False      False  ...     False      True   True           True
...        ...        ...  ...       ...       ...    ...            ...
1995     False      False  ...     False     False  False          False
1996     False      False  ...     False      True   True           True
1997     False      False  ...      True      True   True           True
1998     False      False  ...      True      True   True           True
1999     False      False  ...      True      True   True           True

      geo_is_contact  geo_is_friend  geo_is_family  url_o  height_o  width_o
0               True           True           True   True      True     True
1              False          False          False  False     False    False
2              False          False          False  False     False    False
3               True           True           True  False     False    False
4               True           True           True  False     False    False
...              ...            ...            ...    ...       ...      ...
1995           False          False          False  False     False    False
1996            True           True           True  False     False    False
1997            True           True           True   True      True     True
1998            True           True           True  False     False    False
1999            True           True           True   True      True     True

[2000 rows x 34 columns]

In [5]:
data.isna()

,id,owner,secret,server,farm,title,ispublic,isfriend,isfamily,ownername,...,o_height,place_id,woeid,geo_is_public,geo_is_contact,geo_is_friend,geo_is_family,url_o,height_o,width_o
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1996,False,False,False,False,False,False,False,False,False,False,...,False,True,True,True,True,True,True,False,False,False
1997,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1998,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,False,False,False
1999,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True

In [8]:
search = pd.DataFrame.duplicated(data)
print(data)
print()
print(search[search == True])

               id          owner      secret  server  farm  \
0     51193420302   12012973@N00  a2fe5cedc6   65535    66
1     51194989028   48447300@N02  8ef61baf57   65535    66
2     51195548179   48447300@N02  558b0b2bdc   65535    66
3     51197606714  181609802@N03  0ae5f83ab2   65535    66
4     51197298805   23307937@N04  28df630fab   65535    66
...           ...            ...         ...     ...   ...
1995  51006906196  158292715@N07  cb783a180e   65535    66
1996  51016540858   23974506@N05  69666368d9   65535    66
1997  51016132921   83818540@N00  e866e52464   65535    66
1998  51016826177   67212223@N05  23b7f85e0a   65535    66
1999  51016877196   64116329@N04  5dd1143853   65535    66

                                       title  ispublic  isfriend  isfamily  \
0                                     Frends         1         0         0
1     Cousins having dinner - Happy Caturday         1         0         0
2      Waiting for her fill - Happy Caturday         1         0         0
3                         Jessie am 15.05.21         1         0         0
4                         Introducing Gentil         1         0         0
...                                      ...       ...       ...       ...
1995                           IMG_4422 Lola         1         0         0
1996                        #133 - Just Bebe         1         0         0
1997                                 Resting         1         0         0
1998                          Regard de chat         1         0         0
1999                                 Go away         1         0         0

               ownername  ...  o_height place_id      woeid  geo_is_public  \
0      Valentine Kleyner  ...       NaN      NaN        NaN            NaN
1        Finn Frode (DK)  ...    1536.0           2619940.0            1.0
2        Finn Frode (DK)  ...    1536.0           2619940.0            1.0
3              rosapfote  ...       NaN      NaN        NaN            NaN
4            frankieleon  ...    3024.0      NaN        NaN            NaN
...                  ...  ...       ...      ...        ...            ...
1995  Fernando Sa Rapita  ...    4000.0           8299683.0            1.0
1996              n8fire  ...    5464.0      NaN        NaN            NaN
1997             Arutemu  ...       NaN      NaN        NaN            NaN
1998            Mikasper  ...       NaN      NaN        NaN            NaN
1999            ..Rini..  ...       NaN      NaN        NaN            NaN

     geo_is_contact geo_is_friend geo_is_family  \
0               NaN           NaN           NaN
1               0.0           0.0           0.0
2               0.0           0.0           0.0
3               NaN           NaN           NaN
4               NaN           NaN           NaN
...             ...           ...           ...
1995            0.0           0.0           0.0
1996            NaN           NaN           NaN
1997            NaN           NaN           NaN
1998            NaN           NaN           NaN
1999            NaN           NaN           NaN

                                                  url_o  height_o  width_o
0                                                   NaN       NaN      NaN
1     https://live.staticflickr.com/65535/5119498902...    1536.0   2560.0
2     https://live.staticflickr.com/65535/5119554817...    1536.0   2048.0
3     https://live.staticflickr.com/65535/5119760671...    3120.0   4160.0
4     https://live.staticflickr.com/65535/5119729880...    3024.0   4032.0
...                                                 ...       ...      ...
1995  https://live.staticflickr.com/65535/5100690619...    4000.0   6000.0
1996  https://live.staticflickr.com/65535/5101654085...    5464.0   8192.0
1997                                                NaN       NaN      NaN
1998  https://live.staticflickr.com/65535/5101682617...    1200.0   1800.0
1999                                                NaN       NaN      NaN

[2000 rows x 34 columns]

Series([], dtype: bool)

In [6]:
print(data.drop_duplicates())

               id          owner      secret  server  farm  \
0     51193420302   12012973@N00  a2fe5cedc6   65535    66
1     51194989028   48447300@N02  8ef61baf57   65535    66
2     51195548179   48447300@N02  558b0b2bdc   65535    66
3     51197606714  181609802@N03  0ae5f83ab2   65535    66
4     51197298805   23307937@N04  28df630fab   65535    66
...           ...            ...         ...     ...   ...
1995  51006906196  158292715@N07  cb783a180e   65535    66
1996  51016540858   23974506@N05  69666368d9   65535    66
1997  51016132921   83818540@N00  e866e52464   65535    66
1998  51016826177   67212223@N05  23b7f85e0a   65535    66
1999  51016877196   64116329@N04  5dd1143853   65535    66

                                       title  ispublic  isfriend  isfamily  \
0                                     Frends         1         0         0
1     Cousins having dinner - Happy Caturday         1         0         0
2      Waiting for her fill - Happy Caturday         1         0         0
3                         Jessie am 15.05.21         1         0         0
4                         Introducing Gentil         1         0         0
...                                      ...       ...       ...       ...
1995                           IMG_4422 Lola         1         0         0
1996                        #133 - Just Bebe         1         0         0
1997                                 Resting         1         0         0
1998                          Regard de chat         1         0         0
1999                                 Go away         1         0         0

               ownername  ...  o_height place_id      woeid  geo_is_public  \
0      Valentine Kleyner  ...       NaN      NaN        NaN            NaN
1        Finn Frode (DK)  ...    1536.0           2619940.0            1.0
2        Finn Frode (DK)  ...    1536.0           2619940.0            1.0
3              rosapfote  ...       NaN      NaN        NaN            NaN
4            frankieleon  ...    3024.0      NaN        NaN            NaN
...                  ...  ...       ...      ...        ...            ...
1995  Fernando Sa Rapita  ...    4000.0           8299683.0            1.0
1996              n8fire  ...    5464.0      NaN        NaN            NaN
1997             Arutemu  ...       NaN      NaN        NaN            NaN
1998            Mikasper  ...       NaN      NaN        NaN            NaN
1999            ..Rini..  ...       NaN      NaN        NaN            NaN

     geo_is_contact geo_is_friend geo_is_family  \
0               NaN           NaN           NaN
1               0.0           0.0           0.0
2               0.0           0.0           0.0
3               NaN           NaN           NaN
4               NaN           NaN           NaN
...             ...           ...           ...
1995            0.0           0.0           0.0
1996            NaN           NaN           NaN
1997            NaN           NaN           NaN
1998            NaN           NaN           NaN
1999            NaN           NaN           NaN

                                                  url_o  height_o  width_o
0                                                   NaN       NaN      NaN
1     https://live.staticflickr.com/65535/5119498902...    1536.0   2560.0
2     https://live.staticflickr.com/65535/5119554817...    1536.0   2048.0
3     https://live.staticflickr.com/65535/5119760671...    3120.0   4160.0
4     https://live.staticflickr.com/65535/5119729880...    3024.0   4032.0
...                                                 ...       ...      ...
1995  https://live.staticflickr.com/65535/5100690619...    4000.0   6000.0
1996  https://live.staticflickr.com/65535/5101654085...    5464.0   8192.0
1997                                                NaN       NaN      NaN
1998  https://live.staticflickr.com/65535/5101682617...    1200.0   1800.0
1999                                                NaN       NaN      NaN

[2000 rows x 34 columns]

In [7]:
data.dropna

<bound method DataFrame.dropna of                id          owner      secret  server  farm  \
0     51193420302   12012973@N00  a2fe5cedc6   65535    66
1     51194989028   48447300@N02  8ef61baf57   65535    66
2     51195548179   48447300@N02  558b0b2bdc   65535    66
3     51197606714  181609802@N03  0ae5f83ab2   65535    66
4     51197298805   23307937@N04  28df630fab   65535    66
...           ...            ...         ...     ...   ...
1995  51006906196  158292715@N07  cb783a180e   65535    66
1996  51016540858   23974506@N05  69666368d9   65535    66
1997  51016132921   83818540@N00  e866e52464   65535    66
1998  51016826177   67212223@N05  23b7f85e0a   65535    66
1999  51016877196   64116329@N04  5dd1143853   65535    66

                                       title  ispublic  isfriend  isfamily  \
0                                     Frends         1         0         0
1     Cousins having dinner - Happy Caturday         1         0         0
2      Waiting for her fill - Happy Caturday         1         0         0
3                         Jessie am 15.05.21         1         0         0
4                         Introducing Gentil         1         0         0
...                                      ...       ...       ...       ...
1995                           IMG_4422 Lola         1         0         0
1996                        #133 - Just Bebe         1         0         0
1997                                 Resting         1         0         0
1998                          Regard de chat         1         0         0
1999                                 Go away         1         0         0

               ownername  ...  o_height place_id      woeid  geo_is_public  \
0      Valentine Kleyner  ...       NaN      NaN        NaN            NaN
1        Finn Frode (DK)  ...    1536.0           2619940.0            1.0
2        Finn Frode (DK)  ...    1536.0           2619940.0            1.0
3              rosapfote  ...       NaN      NaN        NaN            NaN
4            frankieleon  ...    3024.0      NaN        NaN            NaN
...                  ...  ...       ...      ...        ...            ...
1995  Fernando Sa Rapita  ...    4000.0           8299683.0            1.0
1996              n8fire  ...    5464.0      NaN        NaN            NaN
1997             Arutemu  ...       NaN      NaN        NaN            NaN
1998            Mikasper  ...       NaN      NaN        NaN            NaN
1999            ..Rini..  ...       NaN      NaN        NaN            NaN

     geo_is_contact geo_is_friend geo_is_family  \
0               NaN           NaN           NaN
1               0.0           0.0           0.0
2               0.0           0.0           0.0
3               NaN           NaN           NaN
4               NaN           NaN           NaN
...             ...           ...           ...
1995            0.0           0.0           0.0
1996            NaN           NaN           NaN
1997            NaN           NaN           NaN
1998            NaN           NaN           NaN
1999            NaN           NaN           NaN

                                                  url_o  height_o  width_o
0                                                   NaN       NaN      NaN
1     https://live.staticflickr.com/65535/5119498902...    1536.0   2560.0
2     https://live.staticflickr.com/65535/5119554817...    1536.0   2048.0
3     https://live.staticflickr.com/65535/5119760671...    3120.0   4160.0
4     https://live.staticflickr.com/65535/5119729880...    3024.0   4032.0
...                                                 ...       ...      ...
1995  https://live.staticflickr.com/65535/5100690619...    4000.0   6000.0
1996  https://live.staticflickr.com/65535/5101654085...    5464.0   8192.0
1997                                                NaN       NaN      NaN
1998  https://live.staticflickr.com/65535/5101682617...    1200.0   1800.0
1999                                                NaN       NaN      NaN

[2000 rows x 34 columns]>